# Form implementation generated from reading ui file 'UI_main.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Kart_Data_Transfer(object):
    def setupUi(self, Kart_Data_Transfer:QtWidgets.QMainWindow):
        Kart_Data_Transfer.setObjectName("Kart_Data_Transfer")
        Kart_Data_Transfer.resize(402, 307)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        Kart_Data_Transfer.setFont(font)
        self.Data_select = QtWidgets.QComboBox(parent=Kart_Data_Transfer)
        self.Data_select.setGeometry(QtCore.QRect(40, 70, 151, 20))
        self.Data_select.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.Data_select.setObjectName("Data_select")
        self.Title = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.Title.setGeometry(QtCore.QRect(20, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Data_name = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.Data_name.setGeometry(QtCore.QRect(40, 50, 151, 16))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Data_name.setFont(font)
        self.Data_name.setObjectName("Data_name")
        self.Formula = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.Formula.setGeometry(QtCore.QRect(40, 100, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Formula.setFont(font)
        self.Formula.setObjectName("Formula")
        self.Default_param = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.Default_param.setGeometry(QtCore.QRect(40, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Default_param.setFont(font)
        self.Default_param.setObjectName("Default_param")
        self.Param_in_xml = QtWidgets.QLineEdit(parent=Kart_Data_Transfer)
        self.Param_in_xml.setGeometry(QtCore.QRect(40, 180, 131, 21))
        self.Param_in_xml.setObjectName("Param_in_xml")
        self.Param_in_game = QtWidgets.QLineEdit(parent=Kart_Data_Transfer)
        self.Param_in_game.setGeometry(QtCore.QRect(250, 180, 131, 21))
        self.Param_in_game.setObjectName("Param_in_game")
        self.xml_title_1 = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.xml_title_1.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.xml_title_1.setObjectName("xml_title_1")
        self.ingame_title_1 = QtWidgets.QLabel(parent=Kart_Data_Transfer)
        self.ingame_title_1.setGeometry(QtCore.QRect(250, 160, 91, 16))
        self.ingame_title_1.setObjectName("ingame_title_1")
        self.Add_formula = QtWidgets.QPushButton(parent=Kart_Data_Transfer)
        self.Add_formula.setGeometry(QtCore.QRect(40, 250, 75, 23))
        self.Add_formula.setObjectName("Add_formula")

        self.retranslateUi(Kart_Data_Transfer)
        QtCore.QMetaObject.connectSlotsByName(Kart_Data_Transfer)

    def retranslateUi(self, Kart_Data_Transfer:QtWidgets.QWidget):
        _translate = QtCore.QCoreApplication.translate
        Kart_Data_Transfer.setWindowTitle(_translate("Kart_Data_Transfer", "跑跑卡丁車 車輛數據轉換器"))
        self.Title.setText(_translate("Kart_Data_Transfer", "車輛數據轉換"))
        self.Data_name.setText(_translate("Kart_Data_Transfer", "數據名稱"))
        self.Formula.setText(_translate("Kart_Data_Transfer", "Formula"))
        self.Default_param.setText(_translate("Kart_Data_Transfer", "Default:"))
        self.xml_title_1.setText(_translate("Kart_Data_Transfer", "Param in xml file"))
        self.ingame_title_1.setText(_translate("Kart_Data_Transfer", "Param in game"))
        self.Add_formula.setText(_translate("Kart_Data_Transfer", "新增數據"))
